"""Constantes globales du jeu."""

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "Deadweight"

TILE_SIZE = 32

PLAYER_SPEED = 4
PLAYER_MAX_HP = 100

GHOST_MODE_DURATION = 10.0
GHOST_MODE_SPEED = 5
POISON_VIAL_START_COUNT = 3
RESURRECTION_VIAL_START_COUNT = 3
